import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    coverage: {
      provider: 'v8',
      include: [
        'src/autograd/accumulator.js',
        'src/autograd/engine.js',
        'src/autograd/grad_mode.js',
        'src/autograd/node.js',
        'src/autograd/registry.js',
        'src/autograd/function/**/*.js',
        'src/tensor/types/dtype.js',
        'src/tensor/types/layout.js',
        'src/tensor/utils/shape_utils.js',
        'src/tensor/core/storage_impl.js',
        'src/tensor/core/storage.js',
        'src/tensor/core/tensor.js',
        'src/tensor/core/autograd_meta.js',
        'src/tensor/factory/**/*.js',
        'src/tensor/view/view_utils.js',
        'src/tensor/ops/registry.js',
        'src/tensor/native/registration.js',
        'src/dispatcher/dispatch_key.js',
        'src/dispatcher/guard.js',
        'src/dispatcher/fallback.js',
        'src/dispatcher/operator_entry.js',
        'src/dispatcher/operator_schema.js',
        'src/nn/module.js',
        'src/nn/parameter.js',
        'src/nn/init.js',
        'src/nn/modules/**/*.js',
        'src/compiler/ir/graph/types.js',
        'src/compiler/ir/graph/value.js',
        'src/compiler/ir/graph/operation.js',
        'src/compiler/ir/graph/block.js',
        'src/compiler/ir/graph/function.js',
        'src/compiler/ir/graph/module.js',
        'src/compiler/ir/graph/op_registry.js',
        'src/compiler/ir/graph/blocked_layout.js',
        'src/compiler/ir/graph/quantization_types.js',
        'src/compiler/ir/graph/ops/helpers.js',
        'src/compiler/ir/tensor/buffer.js',
        'src/compiler/ir/tensor/nodes.js',
        'src/compiler/ir/tensor/tensor_types.js',
        'src/compiler/analysis/use_def.js',
        'src/compiler/analysis/analysis_manager.js',
        'src/compiler/analysis/memory_effect.js',
        'src/compiler/analysis/liveness.js',
        'src/compiler/analysis/shape_analysis.js',
        'src/compiler/analysis/dtype_analysis.js',
        'src/compiler/analysis/dominance.js',
        'src/compiler/analysis/sym_int.js',
        'src/compiler/analysis/alias_analysis.js',
        'src/compiler/passes/pass.js',
        'src/compiler/passes/pass_manager.js',
        'src/compiler/passes/pass_manager.js',
        'src/compiler/passes/lowering/lowering_registry.js',
        'src/compiler/pipeline/trace.js',
        'src/compiler/cost_model/features.js',
        'src/compiler/schedule/dep_analysis.js',
        'src/compiler/schedule/schedule_state.js',
        'src/compiler/schedule/validator.js',
        'src/compiler/autotune/tuning_db.js',
        'src/backend/target.js',
        'src/backend/dtype_map.js',
      ],
      thresholds: {
        lines: 83,
        functions: 85,
        branches: 65,
        statements: 80,
      },
    },
  },
});
